/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'subaru' at '15/09/17 22:30' with Gradle 2.2.1
 *
 * @author subaru, @date 15/09/17 22:30
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
